apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: web ## The name of the partition containing the service
spec:
  services:
    - name: mesh-gateway
      namespace: default
      consumers:
        - partition: api